### ISSUE TITLE
Error in TTS module

### ISSUE THREAD

**Issue by ghost** [nodef/extra-tts#3]
`$ echo "Dead man walking." | tts -p amazon -vn Matthew`
`/node_modules/.registry.npmjs.org/extra-tts/1.0.5/node_modules/extra-tts/index.js:14`
`  log: boolean(E['TTS_LOG']||'0'),`
      ` ^`

`TypeError: boolean is not a function`
    `at Object.<anonymous> (/rbd/pnpm-volume/78feb314-1856-4944-ac20-889e69374c19/node_modules/.registry.npmjs.org/extra-tts/1.0.5/node_modules/extra-tts/index.js:14:8)`
    `at Module._compile (internal/modules/cjs/loader.js:654:30)`
    `at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)`
    `at Module.load (internal/modules/cjs/loader.js:566:32)`
    `at tryModuleLoad (internal/modules/cjs/loader.js:506:12)`
    `at Function.Module._load (internal/modules/cjs/loader.js:498:3)`
    `at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)`
    `at startup (internal/bootstrap/node.js:201:19)`
    `at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)`

**Comment by wolfram77** [comment]
@krvstianeq i update that line of code, but need some time to check if there are any other errors. If you find any further errors comment it here.

**Comment by wolfram77** [comment]
@krvstianeq did it work?

**Comment by ghost** [comment]
yes thx

**Comment by kevin4dhd** [comment]
the same error, how to fix?

**Comment by wolfram77** [comment]
I had skipped braces for `boolean`. It should be working now.

```javascript
const boolean = require('boolean');
```
->
```javascript
const {boolean} = require('boolean');
```
